/oak:
  ros__parameters:
    camera:
      i_mx_id: 14442C10014DD7D600  # Left Camera
      i_enable_imu: true
      i_enable_ir: true
      i_nn_type: spatial
      i_pipeline_type: RGBD
      i_laser_dot_brightness: 1100
    left:
      i_board_socket_id: 1
      i_enable_feature_tracker: false
      i_fps: 30.0
      i_height: 400
      i_max_q_size: 30
      i_publish_compressed: false
      i_publish_topic: true
      i_resolution: 720P
      i_update_ros_base_time_on_ros_msg: false
      i_width: 640
      r_exposure: 10000
      r_iso: 400
      r_set_man_exposure: true
    rgb:
      i_board_socket_id: 0
      i_enable_feature_tracker: false
      i_enable_lazy_publisher: false
      i_enable_preview: false
      i_fps: 30.0
      i_height: 400
      i_keep_preview_aspect_ratio: true
      i_max_q_size: 30
      i_output_isp: false
      i_preview_height: 400
      i_preview_size: 720
      i_preview_width: 640
      i_publish_compressed: false
      i_publish_topic: true
      i_resolution: 720P
      i_reverse_stereo_socket_order: false
      i_sensor_img_orientation: AUTO
      i_set_isp3a_fps: false
      i_set_isp_scale: true
      i_simulate_from_topic: false
      i_simulated_topic_name: ""
      i_synced: false
      i_update_ros_base_time_on_ros_msg: false
      i_width: 640
      r_exposure: 15000
      r_focus: 125
      r_iso: 1000
      r_set_man_exposure: true
      r_set_man_focus: true
      r_set_man_whitebalance: false
      r_whitebalance: 3300
    right:
      i_board_socket_id: 2
      i_enable_feature_tracker: false
      i_fps: 30.0
      i_height: 400
      i_max_q_size: 30
      i_publish_compressed: false
      i_publish_topic: true
      i_resolution: 720P
      i_update_ros_base_time_on_ros_msg: false
      i_width: 640
      r_exposure: 10000
      r_iso: 400
      r_set_man_exposure: true

    stereo:
      i_align_depth: true
      i_bilateral_sigma: 0
      i_board_socket_id: 0
      i_depth_filter_size: 5
      i_depth_preset: HIGH_ACCURACY
      i_disparity_width: DISPARITY_96
      i_enable_alpha_scaling: false
      i_alpha_scaling: 0.0
      i_enable_brightness_filter: false
      i_brightness_filter_min_brightness: 0
      i_brightness_filter_max_brightness: 256
      i_enable_companding: false
      i_enable_decimation_filter: false
      i_decimation_filter_decimation_mode: PIXEL_SKIPPING
      i_decimation_filter_decimation_factor: 1
      i_enable_disparity_shift: false
      i_disparity_shift: 0
      i_enable_distortion_correction: true
      i_enable_lazy_publisher: false
      i_enable_spatial_filter: true
      i_spatial_filter_hole_filling_radius: 2
      i_spatial_filter_alpha: 0.5
      i_spatial_filter_delta: 20
      i_spatial_filter_iterations: 1
      i_enable_spatial_nn: false
      i_enable_speckle_filter: true
      i_speckle_filter_speckle_range: 25
      i_enable_temporal_filter: true
      i_temporal_filter_alpha: 0.4
      i_temporal_filter_delta: 20
      i_temporal_filter_persistency: VALID_2_IN_LAST_4
      i_enable_threshold_filter: true
      i_threshold_filter_min_range: 100
      i_threshold_filter_max_range: 6500
      i_exposure_offset: 0
      i_extended_disp: false
      i_get_base_device_timestamp: false
      i_height: 400
      i_left_rect_add_exposure_offset: false
      i_left_rect_enable_feature_tracker: false
      i_left_rect_exposure_offset: 0
      i_left_rect_low_bandwidth: false
      i_left_rect_low_bandwidth_bitrate: 0
      i_left_rect_low_bandwidth_ffmpeg_encoder: libx264
      i_left_rect_low_bandwidth_frame_freq: 30
      i_left_rect_low_bandwidth_profile: 4
      i_left_rect_low_bandwidth_quality: 50
      i_left_rect_publish_compressed: false
      i_left_rect_synced: true
      i_left_socket_id: 1
      i_low_bandwidth: false
      i_low_bandwidth_bitrate: 0
      i_low_bandwidth_ffmpeg_encoder: libx264
      i_low_bandwidth_profile: 4
      i_low_bandwidth_quality: 50
      i_lr_check: true
      i_lrc_threshold: 10
      i_max_q_size: 30
      i_output_disparity: false
      i_publish_left_rect: false
      i_publish_right_rect: false
      i_publish_synced_rect_pair: false
      i_publish_topic: true
      i_rectify_edge_fill_color: 0
      i_reverse_stereo_socket_order: false
      i_right_rect_add_exposure_offset: false
      i_right_rect_enable_feature_tracker: false
      i_right_rect_exposure_offset: 0
      i_right_rect_low_bandwidth: false
      i_right_rect_low_bandwidth_bitrate: 0
      i_right_rect_low_bandwidth_ffmpeg_encoder: libx264
      i_right_rect_low_bandwidth_frame_freq: 30
      i_right_rect_low_bandwidth_profile: 4
      i_right_rect_low_bandwidth_quality: 50
      i_right_rect_publish_compressed: false
      i_right_rect_synced: true
      i_right_socket_id: 2
      i_set_disparity_to_depth_use_spec_translation: false
      i_set_input_size: false
      i_socket_name: rgb
      i_spatial_nn_source: right
      i_stereo_conf_threshold: 180
      i_subpixel: true
      i_subpixel_fractional_bits: 5
      i_synced: false
      i_update_ros_base_time_on_ros_msg: false
      i_width: 640
      use_sim_time: false