# Static transform from base_link to oak_right_frame
transform:
  translation:
    x: -0.0800  # radius * cos(-120°)
    y: -0.1386  # radius * sin(-120°)
    z: 0.2418
  rotation:
    roll: 0.0
    pitch: 0.0
    yaw: -2.0944  # -120 degrees in radians
  parent_frame: "base_link"
  child_frame: "oak_right_frame"