# Static transform from base_link to oak_front_frame
transform:
  translation:
    x: 0.20752305
    y: 0.0
    z: 0.27459373
  rotation:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  parent_frame: "base_link"
  child_frame: "oak_front_frame"