<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>adam_bringup</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="mahesh.kate@emagegroup.com">emage</maintainer>
  <license>TODO: License declaration</license>
  <depend>action_msgs</depend>
  <depend>adam_message</depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
